preposicoes = [
    'a', 'ante', 'após', 'até', 'com', 'contra', 'de', 'da', 'do', 'desde', 'em', 'na', 'no', 'entre',
    'para', 'pra', 'pro', 'perante', 'por', 'sem', 'sob', 'sobre', 'trás'
]

siglas = {
    'Sr': 'Senhor',
    'Sra': 'Senhora',
    'Dr': 'Doutor',
    'Dra': 'Doutora',
    'Prof': 'Professor',
    'Profa': 'Professora',
    'Pres': 'Presidente',
    'Vice-Pres': 'Vice-presidente',
    'Gov': 'Governador',
    'Pref': 'Prefeito',
    'Adv': 'Advogado',
    'Dr': 'Doutor',
    'Méd': 'Médico',
    'Med': 'Médico',
    'Eng': 'Engenheiro',
    'Jorn': 'Jornalista',
    'Pe': 'Padre',
    'Pr': 'pastor',
    'Gen Ex': 'General de Exército',
    'Gen Div': 'General de Divisão',
    'Gen Bda': 'General de Brigada',
    'Cel': 'Coronel',
    'Ten Cel': 'Tenente-Coronel',
    'Maj': 'Major',
    'Cap': 'Capitão',
    '1º Ten': 'Primeiro-Tenente',
    '2º Ten': 'Segundo-Tenente',
    'Asp': 'Aspirante-a-Oficial',
    'S Ten': 'Subtenente',
    '1º Sgt': 'Primeiro-Sargento',
    '2º Sgt': 'Segundo-Sargento',
    '3º Sgt': 'Terceiro-Sargento',
    'Cb': 'Cabo',
    'Sd': 'Soldado',
    'Am': 'Almirante de Esquadra',
    'Ae': 'Almirante',
    'Ve': 'Vice-Almirante',
    'Ce': 'Contra-Almirante',
    'Cmg': 'Capitão de Mar e Guerra',
    'Cf': 'Capitão de Fragata',
    'Cc': 'Capitão de Corveta',
    'Ct': 'Capitão-Tenente',
    'Asp': 'Aspirante',
    'So': 'Suboficial',
    'Mn': 'Marinheiro',
    'Maj Brig': 'Major-Brigadeiro',
    'Brg': 'Brigadeiro',
    'Cel Av': 'Coronel Aviador',
    'Cel Int': 'Coronel Intendente',
    'Cel Inf': 'Coronel Infantaria',
    'Ten Cel Av': 'Tenente-Coronel Aviador',
    'Ten Cel Int': 'Tenente-Coronel Intendente',
    'Ten Cel Inf': 'Tenente-Coronel Infantaria',
    'Maj Av': 'Major Aviador',
    'Maj Int': 'Major Intendente',
    'Maj Inf': 'Major Infantaria',
    'Cap Av': 'Capitão Aviador',
    'Cap Int': 'Capitão Intendente',
    'Cap Inf': 'Capitão Infantaria',
    '1º Ten Av': 'Primeiro-Tenente Aviador',
    '1º Ten Int': 'Primeiro-Tenente Intendente',
    '1º Ten Inf': 'Primeiro-Tenente Infantaria',
    '2º Ten Av': 'Segundo-Tenente Aviador',
    '2º Ten Int': 'Segundo-Tenente Intendente',
    '2º Ten Inf': 'Segundo-Tenente Infantaria',
    'Av': 'Avenida',
    'R': 'Rua',
    'Pça': 'Praça',
    'Al': 'Alameda',
    'Trav': 'Travessa',
    'Rod': 'Rodovia',
    'Estr': 'Estrada',
    'Viad': 'Viaduto',
    'Pass': 'Passagem',
    'Lgo': 'Largo',
    'Vd': 'Viaduto',
    'Est': 'Estação',
    'Rv': 'Reversa',
    'Pnt': 'Ponte',
    'BC': 'Beco',
    'Bl': 'Bloco',
    'Cond': 'Condomínio',
    'Ch': 'Chácara'
}

